### ISSUE TITLE
can't find 'system 390' which in libc6_2.23-0ubuntu10_amd64 or libc6_2.23-0ubuntu11_amd64

### ISSUE THREAD

**Issue by lonnywong** [niklasb/libc-database#28]
```
./find system 390
```
https://libc.blukat.me/?q=system%3A390

**Comment by blukat29** [comment]
@lonnywang I haven't been updating libc.blukat.me for a while. It may not reflect the latest libc-database nor the latest OS releases. If you need the latest database, follow what @niklasb said. If you want the web version to be up to date, then please open an issue in my repository or try running your own instance. I think it's the website's problem, not the database problem.

**Comment by lonnywang** [comment]
use https://launchpad.net/ubuntu/xenial/amd64/libc6 ?

**Comment by niklasb** [comment]
@lonnywang we cannot possibly crawl the entire history of all the packages, the database is already almost 1GB large

**Comment by niklasb** [comment]
I don't have a good solution to this, unfortunately

**Comment by lonnywang** [comment]
make it an option ?

**Comment by niklasb** [comment]
Feel free to propose a pull request, we already have framework in place to
enable and disable categories of libraries

**Comment by niklasb** [comment]
Closing this in favor of #37, which will add the feature required to solve this
