### ISSUE TITLE
One URL fails then exit

### ISSUE THREAD

**Issue by brant-ruan** [niklasb/libc-database#4]
Firstly thanks for your great tool!

When I used `./get` to fetch libc for the first time, I came across failure when:
    get_current_ubuntu yakkety i386 libc6
I have not went to see why the above fails, but I found that the `die()` function in `db/libc.sh` will make the whole script exit and `die()` is used in `get_ubuntu()`. So just like in my case, one fails and the rest would not continue to download. Maybe there is some better solution?

Thank you anyway!

**Comment by niklasb** [comment]
This is intended. Otherwise your database might be incomplete without you knowing. I removed the broken download links.
