### ISSUE TITLE
Failed to get package version for rpm musl

### ISSUE THREAD

**Issue by mariuszskon** [niklasb/libc-database#43]
This bug is revealed once the fix https://github.com/niklasb/libc-database/pull/42 is applied.

```
$ ./get rpm
...
Getting rpm
  -> Location: http://rpmfind.net/linux/openmandriva/cooker/repository/x86_64/main/release/musl-1.2.2-1-omv4040.x86_64.rpm
  -> ID: musl-1.2.2-1-omv4040.x86_64
  -> Already have this version, 'rm /root/.libc-database/db/musl-1.2.2-1-omv4040.x86_64.*' to force
Getting package musl locations
Retrying...
Retrying...
Retrying...
Failed to get package version
```

We could (similarly to https://github.com/niklasb/libc-database/pull/42) have this be a non-critical failure but it is more debatable whether this is a good idea.

**Comment by niklasb** [comment]
should be fixed by 460851d300b802f71e9ef1ba4a9f5080ff7f4c37
