### ISSUE TITLE
Add package url to searchengine api

### ISSUE THREAD

**Issue by MrQubo** [niklasb/libc-database#44]
Package url can be retrieved from api by replacing suffix `.so` with `.url` in "download_url" (though it's not documented). It would be useful to have easier access to this, directly from https://libc.rip/api/find endpoint. Maybe under "package_url" or "libs_url"?
This `.url` file was added in this PR: https://github.com/niklasb/libc-database/pull/10

**Comment by niklasb** [comment]
I'll be happy to consider a pull request for this feature
