### ISSUE TITLE
The server does not seem to be working now

### ISSUE THREAD

**Issue by IZAY01** [niklasb/libc-database#47]
api response like this：

▶ curl -X POST -H 'Content-Type: application/json' \       
    --data '{"symbols": ["strcat"]}' \
    'https://libc.rip/api/libc/libc6_2.27-3ubuntu1.2_amd64'
{
  "detail": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",
  "status": 500,
  "title": "Internal Server Error",
  "type": "about:blank"
}

**Comment by vital-information-resource-under-siege** [comment]
One of the feature of my  college project is based on this API.. I am getting worried now... When will the fix be available

**Comment by niklasb** [comment]
@IZAY01 @vital-information-resource-under-siege I'll work on this now.

**Comment by vital-information-resource-under-siege** [comment]
thank u so much @niklasb

**Comment by niklasb** [comment]
@IZAY01 @vital-information-resource-under-siege @peace-maker server should be up again. it was a bit underprovisioned it seems, should work better going forward (I assigned more CPU and RAM resources)

**Comment by IZAY01** [comment]
thanks very much!
