### ISSUE TITLE
Architectures other than x86

### ISSUE THREAD

**Issue by TheDuchy** [niklasb/libc-database#48]
Hi! Are there any plans for adding other architectures than x86? I currently have the need to download them (not for offsets), but while I'm at it I might open a PR. Is this something you would be interested in @niklasb?

**Comment by niklasb** [comment]
thanks for asking @TheDuchy! I think if we want to do this we'll need a proper way to specify not only the subset of distributions to fetch, but also the subset of architectures. Right now I don't have much time to maintain this project, so I can't promise anything in terms of coming up with a concept for that.

**Comment by TheDuchy** [comment]
Ended up actually not needing all of the different versions and I only pulled 1 release manually for all archs so sorry for wasting your time with this proposal :(.
