### ISSUE TITLE
can't find certain libc

### ISSUE THREAD

**Issue by haowayne** [niklasb/libc-database#5]
I try to type in the ./find printf  260 puts f30 as you did in README.md. But it turns out I don't have certain libc as it showed in README.md ...  （Of course, I have downloaded libc-database by using the command ./get ）
Could you please help me??

**Comment by iamahuman** [comment]
certain /ˈsəːt(ə)n  /
    ▸ adjective
    2 [attributive] specific but not explicitly named or stated:
     he raised certain personal problems with me
     the exercise was causing him a certain amount of pain.
    ▪ used when mentioning the name of someone not known to the reader or hearer: a certain General Percy captured the town.

Source: Oxford dictionary

**Comment by iamahuman** [comment]
It looks like the relevant symbol offset information of the version of libc you're working on is missing in the database; if you have a copy, feel free to request its version to be added.

**Comment by niklasb** [comment]
@haowayne The README is outdated, the version of the libc that it used cannot be downloaded from Ubuntu servers anymore. It was probably a non-LTS release.
