### ISSUE TITLE
./get ubuntu cannot be downloaded

### ISSUE THREAD

**Issue by TajangSec** [niklasb/libc-database#53]
**Will download or update for:
Requirements for download or update 'ubuntu' are not met. Please, refer to README.md for installation instructions**
Read the readme.md, but there is no solution in the document

**Comment by lin-peidong** [comment]
In the same situation

**Comment by peace-maker** [comment]
Can you check manually if those tools are in your PATH?

https://github.com/niklasb/libc-database/blob/ea38dde584df9df17bc15b4926acb512d32fc738/common/libc.sh#L135-L144

**Comment by raddyfiy** [comment]
plz sudo apt install binutils rpm2cpio jq
