### ISSUE TITLE
Failed to decompress package (rpm)

### ISSUE THREAD

**Issue by wzsx150** [niklasb/libc-database#56]
hi,
ubuntu 20.04:
./get.sh rpm

Getting rpm
  -> Location: http://rpmfind.net/linux/fedora/linux/updates/35/Everything/x86_64/Packages/g/glibc-2.34-29.fc35.x86_64.rpm
  -> ID: libc-2.34-29.fc35.x86_64
  -> Already have this version, 'rm /home/wzsx150/bin/libc-database/db/libc-2.34-29.fc35.x86_64.*' to force
Getting rpm
  -> Location: http://rpmfind.net/linux/centos-stream/9-stream/BaseOS/x86_64/os/Packages/glibc-2.34-25.el9.x86_64.rpm
  -> ID: libc-2.34-25.el9.x86_64
  -> Downloading package
  -> Extracting package
error: pkg.rpm: signature hdr data: BAD, no. of bytes(27320) out of range
error reading header from package
rpm2cpio failed
cpio: 归档非正常终止
cpio failed
Cannot locate the libc file

how to fix it?

**Comment by TheDuchy** [comment]
Also getting this error. Might troubleshoot later.

**Comment by peace-maker** [comment]
That's a bug in the `rpm2cpio` version packaged with Ubuntu 20.04.
https://bugs.launchpad.net/ubuntu/+source/rpm/+bug/1947120

Try upgrading to Ubuntu 22.04 or compile it from source https://rpm.org/download.html
