### ISSUE TITLE
when use ./get, an error happen

### ISSUE THREAD

**Issue by Byzero512** [niklasb/libc-database#7]
Failed to get package version
Getting 
  -> Location: ubuntu-vivid-i386-libc6
  -> ID: 
  -> Downloading package
Failed to download package from ubuntu-vivid-i386-libc6

**Comment by niklasb** [comment]
I don't see why it should use `./tmp` at all, can you post a `ls -alih tmp/` in the libc-database directory? 

I think the directory is the remainder of some old code, I will push a commit that removes it from the repository.

**Comment by niklasb** [comment]
I believe this should be resolved, please re-open if not

**Comment by Byzero512** [comment]
emmm,it works perfectly.
