### ISSUE TITLE
Getting more versions of glibc

### ISSUE THREAD

**Issue by ducphanduyagentp** [niklasb/libc-database#8]
Hi. I noticed that there are certain versions of glibc not included in the download script. For example, glibc 2.25 is not on Ubuntu, but on Fedora, so it's not downloaded. Is there anyway you can add this to the script? Thank you!

Here's the link to glibc 2.25 on Fedora:
https://fedora.pkgs.org/26/fedora-i386/glibc-2.25-6.fc26.i686.rpm.html

**Comment by niklasb** [comment]
I would be open to pull requests, yes. Note however that the *version* of the library is pretty irrelevant, what's important is the precise compiled binary.
